version: '3.4'

services:
  customers:
    image: mancu37/ecommerceapicustomers:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6002:80"

  orders:
    image: mancu37/ecommerceapiorders:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6003:80"
    
  products:
    image: mancu37/ecommerceapiproducts:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "6001:80"

  search:
    image: mancu37/ecommerceapisearch:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Services__Products=http://10.0.0.4:19081/lil/products/
      - Services__Customers=http://10.0.0.4:19081/lil/customers/
      - Services__Orders=http://10.0.0.4:19081/lil/orders/
    ports:
      - "6004:80"